### ISSUE TITLE
Spawn counterattack helis further away

### ISSUE THREAD

**Issue by VexA3** [BojanOnTheInternet/7Cav_FullSpectrum_V4.Altis#37]

**Comment by BojanOnTheInternet** [comment]
`f◘n_categoryInfantryGarrisonPreInit.sqf

_airSpawnpoint = [OO_GET(_strongpoint,Strongpoint,Position), OO_GET(_strongpoint,Strongpoint,ActivityRadius), 500, 100, _approachDirection select 0, _approachDirection select 1] call SPM_Util_GetAirSpawnpoint;`
