### ISSUE TITLE
Chinook heavy lifting

### ISSUE THREAD

**Issue by BojanOnTheInternet** [BojanOnTheInternet/7Cav_FullSpectrum_V4.Altis#78]
- Add Chinook to Titan permissions
- Remove Chinook from Buffalo permissions (we have never had to transport infantry with this thing)
- Remove Bradley being able to get loaded into vehicles
- Allow Chinook to lift Bradley + all Apollo vehicles

This will make Titan the "Air Apollo". A stranger slot that has access to both fixed and rotary wing, yes, but it makes sense for gameplay.

@Robot-Panda15 can you sign off?

**Comment by Robot-Panda15** [comment]
Keep the perms on the Buff pilots as it'll need a rotary crew, and the 1/A guys will definitely prefer it with it. I have no problems making the Titan have perms as well. Talking vanilla chinook right?

**Comment by BojanOnTheInternet** [comment]
I suppose we could allow Buff pilots to fly the vanilla one (since the RHS? one sucks monkey balls for that) and allow Titan to fly the RHS one since they wont be carrying troops. 

This way we have an infantry transport and a vehicle transport variant.

**Comment by Robot-Panda15** [comment]
I'd prefer to just do the vanilla one, maybe have the unarmed one as the titan variant

**Comment by VexA3** [comment]
- Thinking about the players, Buffalo pilots will want to fly the RHS chinook because.... Its a chinook....
- As for heavy lifting, we can put the vanilla unarmed one for Titan as it is easier to sling with because of the camera and better cockpit glass

**Comment by Robot-Panda15** [comment]
that works for me

**Comment by BojanOnTheInternet** [comment]
The RHS chinook has issues with players touching the ramp and it blowing up. Might be safer for infantry to use the less glitchy one? That said, idrc at the end of the day :)

**Comment by Robot-Panda15** [comment]
nah, if they really want to use the chinook, they can put up with it tbh
